### ISSUE TITLE
file/upload 接口增加更多参数

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaBackendCenter#97]
上传/下载 必选：
- type  
  字符串。可能有战斗场景的图、干员列表的图、……，全混在一起就没法用了

上传/下载 可选：
- classification   
  字符串。比如干员名，只有 XX 干员总识别错，我只需要下载 XX 干员的数据集即可，全下载太大了
- version  
  字符串。某个版本上传的图全有问题，不能用。或者我只需要某些版本的。
    - 上传接口：一个字符串，符合 SemVersion 标准
    - 下载接口：俩字符串，类似 [ vA.B.C, vX.Y.Z ]，上下限符合 SemVersion 标准
- label
  字符串。压缩太麻烦了（bushi，单独传方便点，也好查

**Comment by martinwang2002** [comment]
```
metadata:
   version: v.A.B.C v4.14.0-beta.1
   classification: string
   type: string
   [key as string]: any
image: binary
```

i.e. 加一个metadata就行？
https://docs.spring.io/spring-data/mongodb/docs/current/api/org/springframework/data/mongodb/gridfs/GridFsOperations.html
